# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Ahmed/Documents/GitHub/Martini

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Ahmed/Documents/GitHub/Martini

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Ahmed/Documents/GitHub/Martini/CMakeFiles /mnt/c/Users/Ahmed/Documents/GitHub/Martini/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Ahmed/Documents/GitHub/Martini/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named martini-juxt-patcher

# Build rule for target.
martini-juxt-patcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 martini-juxt-patcher
.PHONY : martini-juxt-patcher

# fast build rule for target.
martini-juxt-patcher/fast:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/build
.PHONY : martini-juxt-patcher/fast

#=============================================================================
# Target rules for targets named libbps

# Build rule for target.
libbps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbps
.PHONY : libbps

# fast build rule for target.
libbps/fast:
	$(MAKE) -f ext/libbps/CMakeFiles/libbps.dir/build.make ext/libbps/CMakeFiles/libbps.dir/build
.PHONY : libbps/fast

#=============================================================================
# Target rules for targets named libiosuhax

# Build rule for target.
libiosuhax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libiosuhax
.PHONY : libiosuhax

# fast build rule for target.
libiosuhax/fast:
	$(MAKE) -f ext/libiosuhax/source/CMakeFiles/libiosuhax.dir/build.make ext/libiosuhax/source/CMakeFiles/libiosuhax.dir/build
.PHONY : libiosuhax/fast

#=============================================================================
# Target rules for targets named wiiurpx

# Build rule for target.
wiiurpx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiiurpx
.PHONY : wiiurpx

# fast build rule for target.
wiiurpx/fast:
	$(MAKE) -f ext/wiiurpxlib/CMakeFiles/wiiurpx.dir/build.make ext/wiiurpxlib/CMakeFiles/wiiurpx.dir/build
.PHONY : wiiurpx/fast

cert_patches/cert_backup.obj: cert_patches/cert_backup.cpp.obj

.PHONY : cert_patches/cert_backup.obj

# target to build an object file
cert_patches/cert_backup.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup.cpp.obj
.PHONY : cert_patches/cert_backup.cpp.obj

cert_patches/cert_backup.i: cert_patches/cert_backup.cpp.i

.PHONY : cert_patches/cert_backup.i

# target to preprocess a source file
cert_patches/cert_backup.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup.cpp.i
.PHONY : cert_patches/cert_backup.cpp.i

cert_patches/cert_backup.s: cert_patches/cert_backup.cpp.s

.PHONY : cert_patches/cert_backup.s

# target to generate assembly for a file
cert_patches/cert_backup.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup.cpp.s
.PHONY : cert_patches/cert_backup.cpp.s

cert_patches/cert_backup_strategy.obj: cert_patches/cert_backup_strategy.cpp.obj

.PHONY : cert_patches/cert_backup_strategy.obj

# target to build an object file
cert_patches/cert_backup_strategy.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup_strategy.cpp.obj
.PHONY : cert_patches/cert_backup_strategy.cpp.obj

cert_patches/cert_backup_strategy.i: cert_patches/cert_backup_strategy.cpp.i

.PHONY : cert_patches/cert_backup_strategy.i

# target to preprocess a source file
cert_patches/cert_backup_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup_strategy.cpp.i
.PHONY : cert_patches/cert_backup_strategy.cpp.i

cert_patches/cert_backup_strategy.s: cert_patches/cert_backup_strategy.cpp.s

.PHONY : cert_patches/cert_backup_strategy.s

# target to generate assembly for a file
cert_patches/cert_backup_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_backup_strategy.cpp.s
.PHONY : cert_patches/cert_backup_strategy.cpp.s

cert_patches/cert_hashes.obj: cert_patches/cert_hashes.cpp.obj

.PHONY : cert_patches/cert_hashes.obj

# target to build an object file
cert_patches/cert_hashes.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_hashes.cpp.obj
.PHONY : cert_patches/cert_hashes.cpp.obj

cert_patches/cert_hashes.i: cert_patches/cert_hashes.cpp.i

.PHONY : cert_patches/cert_hashes.i

# target to preprocess a source file
cert_patches/cert_hashes.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_hashes.cpp.i
.PHONY : cert_patches/cert_hashes.cpp.i

cert_patches/cert_hashes.s: cert_patches/cert_hashes.cpp.s

.PHONY : cert_patches/cert_hashes.s

# target to generate assembly for a file
cert_patches/cert_hashes.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/cert_patches/cert_hashes.cpp.s
.PHONY : cert_patches/cert_hashes.cpp.s

ext/resinfs/source/romfs.obj: ext/resinfs/source/romfs.c.obj

.PHONY : ext/resinfs/source/romfs.obj

# target to build an object file
ext/resinfs/source/romfs.c.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/ext/resinfs/source/romfs.c.obj
.PHONY : ext/resinfs/source/romfs.c.obj

ext/resinfs/source/romfs.i: ext/resinfs/source/romfs.c.i

.PHONY : ext/resinfs/source/romfs.i

# target to preprocess a source file
ext/resinfs/source/romfs.c.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/ext/resinfs/source/romfs.c.i
.PHONY : ext/resinfs/source/romfs.c.i

ext/resinfs/source/romfs.s: ext/resinfs/source/romfs.c.s

.PHONY : ext/resinfs/source/romfs.s

# target to generate assembly for a file
ext/resinfs/source/romfs.c.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/ext/resinfs/source/romfs.c.s
.PHONY : ext/resinfs/source/romfs.c.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/main.cpp.s
.PHONY : main.cpp.s

menu/menu.obj: menu/menu.cpp.obj

.PHONY : menu/menu.obj

# target to build an object file
menu/menu.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu.cpp.obj
.PHONY : menu/menu.cpp.obj

menu/menu.i: menu/menu.cpp.i

.PHONY : menu/menu.i

# target to preprocess a source file
menu/menu.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu.cpp.i
.PHONY : menu/menu.cpp.i

menu/menu.s: menu/menu.cpp.s

.PHONY : menu/menu.s

# target to generate assembly for a file
menu/menu.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu.cpp.s
.PHONY : menu/menu.cpp.s

menu/menu_done.obj: menu/menu_done.cpp.obj

.PHONY : menu/menu_done.obj

# target to build an object file
menu/menu_done.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_done.cpp.obj
.PHONY : menu/menu_done.cpp.obj

menu/menu_done.i: menu/menu_done.cpp.i

.PHONY : menu/menu_done.i

# target to preprocess a source file
menu/menu_done.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_done.cpp.i
.PHONY : menu/menu_done.cpp.i

menu/menu_done.s: menu/menu_done.cpp.s

.PHONY : menu/menu_done.s

# target to generate assembly for a file
menu/menu_done.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_done.cpp.s
.PHONY : menu/menu_done.cpp.s

menu/menu_loading.obj: menu/menu_loading.cpp.obj

.PHONY : menu/menu_loading.obj

# target to build an object file
menu/menu_loading.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_loading.cpp.obj
.PHONY : menu/menu_loading.cpp.obj

menu/menu_loading.i: menu/menu_loading.cpp.i

.PHONY : menu/menu_loading.i

# target to preprocess a source file
menu/menu_loading.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_loading.cpp.i
.PHONY : menu/menu_loading.cpp.i

menu/menu_loading.s: menu/menu_loading.cpp.s

.PHONY : menu/menu_loading.s

# target to generate assembly for a file
menu/menu_loading.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_loading.cpp.s
.PHONY : menu/menu_loading.cpp.s

menu/menu_miiverse_confirm.obj: menu/menu_miiverse_confirm.cpp.obj

.PHONY : menu/menu_miiverse_confirm.obj

# target to build an object file
menu/menu_miiverse_confirm.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_miiverse_confirm.cpp.obj
.PHONY : menu/menu_miiverse_confirm.cpp.obj

menu/menu_miiverse_confirm.i: menu/menu_miiverse_confirm.cpp.i

.PHONY : menu/menu_miiverse_confirm.i

# target to preprocess a source file
menu/menu_miiverse_confirm.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_miiverse_confirm.cpp.i
.PHONY : menu/menu_miiverse_confirm.cpp.i

menu/menu_miiverse_confirm.s: menu/menu_miiverse_confirm.cpp.s

.PHONY : menu/menu_miiverse_confirm.s

# target to generate assembly for a file
menu/menu_miiverse_confirm.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/menu/menu_miiverse_confirm.cpp.s
.PHONY : menu/menu_miiverse_confirm.cpp.s

rpx_patches/rpx_backup.obj: rpx_patches/rpx_backup.cpp.obj

.PHONY : rpx_patches/rpx_backup.obj

# target to build an object file
rpx_patches/rpx_backup.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup.cpp.obj
.PHONY : rpx_patches/rpx_backup.cpp.obj

rpx_patches/rpx_backup.i: rpx_patches/rpx_backup.cpp.i

.PHONY : rpx_patches/rpx_backup.i

# target to preprocess a source file
rpx_patches/rpx_backup.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup.cpp.i
.PHONY : rpx_patches/rpx_backup.cpp.i

rpx_patches/rpx_backup.s: rpx_patches/rpx_backup.cpp.s

.PHONY : rpx_patches/rpx_backup.s

# target to generate assembly for a file
rpx_patches/rpx_backup.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup.cpp.s
.PHONY : rpx_patches/rpx_backup.cpp.s

rpx_patches/rpx_backup_strategy.obj: rpx_patches/rpx_backup_strategy.cpp.obj

.PHONY : rpx_patches/rpx_backup_strategy.obj

# target to build an object file
rpx_patches/rpx_backup_strategy.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup_strategy.cpp.obj
.PHONY : rpx_patches/rpx_backup_strategy.cpp.obj

rpx_patches/rpx_backup_strategy.i: rpx_patches/rpx_backup_strategy.cpp.i

.PHONY : rpx_patches/rpx_backup_strategy.i

# target to preprocess a source file
rpx_patches/rpx_backup_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup_strategy.cpp.i
.PHONY : rpx_patches/rpx_backup_strategy.cpp.i

rpx_patches/rpx_backup_strategy.s: rpx_patches/rpx_backup_strategy.cpp.s

.PHONY : rpx_patches/rpx_backup_strategy.s

# target to generate assembly for a file
rpx_patches/rpx_backup_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_backup_strategy.cpp.s
.PHONY : rpx_patches/rpx_backup_strategy.cpp.s

rpx_patches/rpx_hashes.obj: rpx_patches/rpx_hashes.cpp.obj

.PHONY : rpx_patches/rpx_hashes.obj

# target to build an object file
rpx_patches/rpx_hashes.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_hashes.cpp.obj
.PHONY : rpx_patches/rpx_hashes.cpp.obj

rpx_patches/rpx_hashes.i: rpx_patches/rpx_hashes.cpp.i

.PHONY : rpx_patches/rpx_hashes.i

# target to preprocess a source file
rpx_patches/rpx_hashes.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_hashes.cpp.i
.PHONY : rpx_patches/rpx_hashes.cpp.i

rpx_patches/rpx_hashes.s: rpx_patches/rpx_hashes.cpp.s

.PHONY : rpx_patches/rpx_hashes.s

# target to generate assembly for a file
rpx_patches/rpx_hashes.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_hashes.cpp.s
.PHONY : rpx_patches/rpx_hashes.cpp.s

rpx_patches/rpx_patch.obj: rpx_patches/rpx_patch.cpp.obj

.PHONY : rpx_patches/rpx_patch.obj

# target to build an object file
rpx_patches/rpx_patch.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_patch.cpp.obj
.PHONY : rpx_patches/rpx_patch.cpp.obj

rpx_patches/rpx_patch.i: rpx_patches/rpx_patch.cpp.i

.PHONY : rpx_patches/rpx_patch.i

# target to preprocess a source file
rpx_patches/rpx_patch.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_patch.cpp.i
.PHONY : rpx_patches/rpx_patch.cpp.i

rpx_patches/rpx_patch.s: rpx_patches/rpx_patch.cpp.s

.PHONY : rpx_patches/rpx_patch.s

# target to generate assembly for a file
rpx_patches/rpx_patch.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/rpx_patches/rpx_patch.cpp.s
.PHONY : rpx_patches/rpx_patch.cpp.s

util/iosu_fs.obj: util/iosu_fs.cpp.obj

.PHONY : util/iosu_fs.obj

# target to build an object file
util/iosu_fs.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/iosu_fs.cpp.obj
.PHONY : util/iosu_fs.cpp.obj

util/iosu_fs.i: util/iosu_fs.cpp.i

.PHONY : util/iosu_fs.i

# target to preprocess a source file
util/iosu_fs.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/iosu_fs.cpp.i
.PHONY : util/iosu_fs.cpp.i

util/iosu_fs.s: util/iosu_fs.cpp.s

.PHONY : util/iosu_fs.s

# target to generate assembly for a file
util/iosu_fs.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/iosu_fs.cpp.s
.PHONY : util/iosu_fs.cpp.s

util/log.obj: util/log.c.obj

.PHONY : util/log.obj

# target to build an object file
util/log.c.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/log.c.obj
.PHONY : util/log.c.obj

util/log.i: util/log.c.i

.PHONY : util/log.i

# target to preprocess a source file
util/log.c.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/log.c.i
.PHONY : util/log.c.i

util/log.s: util/log.c.s

.PHONY : util/log.s

# target to generate assembly for a file
util/log.c.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/log.c.s
.PHONY : util/log.c.s

util/titles.obj: util/titles.cpp.obj

.PHONY : util/titles.obj

# target to build an object file
util/titles.cpp.obj:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/titles.cpp.obj
.PHONY : util/titles.cpp.obj

util/titles.i: util/titles.cpp.i

.PHONY : util/titles.i

# target to preprocess a source file
util/titles.cpp.i:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/titles.cpp.i
.PHONY : util/titles.cpp.i

util/titles.s: util/titles.cpp.s

.PHONY : util/titles.s

# target to generate assembly for a file
util/titles.cpp.s:
	$(MAKE) -f CMakeFiles/martini-juxt-patcher.dir/build.make CMakeFiles/martini-juxt-patcher.dir/util/titles.cpp.s
.PHONY : util/titles.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... martini-juxt-patcher"
	@echo "... libbps"
	@echo "... libiosuhax"
	@echo "... wiiurpx"
	@echo "... cert_patches/cert_backup.obj"
	@echo "... cert_patches/cert_backup.i"
	@echo "... cert_patches/cert_backup.s"
	@echo "... cert_patches/cert_backup_strategy.obj"
	@echo "... cert_patches/cert_backup_strategy.i"
	@echo "... cert_patches/cert_backup_strategy.s"
	@echo "... cert_patches/cert_hashes.obj"
	@echo "... cert_patches/cert_hashes.i"
	@echo "... cert_patches/cert_hashes.s"
	@echo "... ext/resinfs/source/romfs.obj"
	@echo "... ext/resinfs/source/romfs.i"
	@echo "... ext/resinfs/source/romfs.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu/menu.obj"
	@echo "... menu/menu.i"
	@echo "... menu/menu.s"
	@echo "... menu/menu_done.obj"
	@echo "... menu/menu_done.i"
	@echo "... menu/menu_done.s"
	@echo "... menu/menu_loading.obj"
	@echo "... menu/menu_loading.i"
	@echo "... menu/menu_loading.s"
	@echo "... menu/menu_miiverse_confirm.obj"
	@echo "... menu/menu_miiverse_confirm.i"
	@echo "... menu/menu_miiverse_confirm.s"
	@echo "... rpx_patches/rpx_backup.obj"
	@echo "... rpx_patches/rpx_backup.i"
	@echo "... rpx_patches/rpx_backup.s"
	@echo "... rpx_patches/rpx_backup_strategy.obj"
	@echo "... rpx_patches/rpx_backup_strategy.i"
	@echo "... rpx_patches/rpx_backup_strategy.s"
	@echo "... rpx_patches/rpx_hashes.obj"
	@echo "... rpx_patches/rpx_hashes.i"
	@echo "... rpx_patches/rpx_hashes.s"
	@echo "... rpx_patches/rpx_patch.obj"
	@echo "... rpx_patches/rpx_patch.i"
	@echo "... rpx_patches/rpx_patch.s"
	@echo "... util/iosu_fs.obj"
	@echo "... util/iosu_fs.i"
	@echo "... util/iosu_fs.s"
	@echo "... util/log.obj"
	@echo "... util/log.i"
	@echo "... util/log.s"
	@echo "... util/titles.obj"
	@echo "... util/titles.i"
	@echo "... util/titles.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

